boeker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('search.urls')),
    path('', include('lists.urls')),
]

lists/urls.py
from django.urls import path
from search import urls
from . import views

app_name = 'lists'
urlpatterns = [
    path('listing', views.listing, name='listing'),
    path('list', views.cur_list, name='list'),
    path('profile', views.profile, name='profile'),
    path('library', views.library, name='library'),
    path('password', views.change_password, name='password')
]

lists/models.py
from django.db import models


class Book(models.Model):
    title = models.TextField()
    authors = models.TextField()
    publisher = models.CharField(max_length=200)
    pub_date = models.DateField()
    description = models.TextField()
    page_count = models.IntegerField()
    categories = models.TextField()
    language = models.CharField(max_length=2)
    image_link = models.TextField()

    def __str__(self):
        return f'{self.title} ({self.pub_date}) - {self.page_count} pp.'

lists/forms.py
from django.contrib.auth.models import User
from django import forms


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email']

    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'email']:
            self.fields[fieldname].help_text = None

lists/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm
import hashlib

from .api import search_books


class List:
    def __init__(self, name, size, books=None):
        self.name = name
        self.size = size
        self.books = books


def listing(request):
    lists = []
    list1 = List("Добавленные", 4)
    lists.append(list1)
    if request.method == 'POST':
        query = request.POST
        try:
            name = query.__getitem__('list_name')
        except KeyError:
            pass
        else:
            list2 = List(name, 0)
            lists.append(list2)
    context = {
        'lists': tuple(lists),
    }
    return render(request, 'lists/lists.html', context)


def cur_list(request):
    books = search_books('None')[:4]
    list2 = List("Добавленные", 4, books)
    context = {
        'list': list2,
    }
    return render(request, 'lists/list.html', context)


def gen_avatar_url(user):
    if user.is_authenticated:
        email = user.email.strip().lower()
        avatar_hash, size = hashlib.md5(email.encode('utf-8')).hexdigest(), 512
        return f'https://gravatar.com/avatar/{avatar_hash}?s={size}'
    else:
        return


@login_required
def profile(request):
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = UserUpdateForm(instance=request.user)

    context = {
        'avatar_url': gen_avatar_url(request.user),
        'form': form,
    }
    return render(request, 'lists/profile.html', context)


@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        form.fields['new_password1'].help_text = None
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('profile')
    else:
        form = PasswordChangeForm(request.user)
        form.fields['new_password1'].help_text = None

    context = {
        'avatar_url': gen_avatar_url(request.user),
        'form': form,
    }
    return render(request, 'lists/change_password.html', context)


def library(request):
    books = search_books('The Remains of the Day')[:4]
    context = {
        'books': books,
    }
    return render(request, 'lists/library.html', context)

lists/templates/lists/base - без параллакса.html
<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

		{% block title %}
		<title> title </title> 
		{% endblock %}

		
		<style>
			@import url('https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;400&display=swap');
			body {
				font-family: 'Roboto Slab';
				background: url(https://mengembangkandiri.com/wp-content/uploads/2019/12/susan-yin-2JIvboGLeho-unsplash-768x513.jpg) no-repeat center top fixed;
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                 background-size: cover;
			}
		</style>

		{% block style %}
		{% endblock %}

	</head>
	<body>

		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

		{% block precontent %}
		{% endblock %}
		<!-- navigation bar starts -->
		<header>
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<div class="container-fluid">
				<!-- navbar brand starts -->
				<a class="navbar-brand" href="{% url 'home' %}">KNИGИ</a>
				<!-- navbar brand ends -->
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
				</button>
				<!-- navbar menu starts -->
				<div class="collapse navbar-collapse justify-content-between" id="navbarNav">
					<!-- left navbar menu starts -->
					<ul class="navbar-nav">
						<li class="nav-item">
						<a class="nav-link" href="{% url 'lists:library' %}">Библиотека</a>
						</li>
						<li class="nav-item">
						<a class="nav-link" href="{% url 'lists:listing' %}">Списки</a>
						</li>
						<li class="nav-item">
						<a class="nav-link" href="{% url 'lists:profile' %}">Настройки</a>
						</li>
					</ul>
					<!-- left navbar menu ends -->
					<!-- right navbar menu starts -->
					<ul class="navbar-nav">
						<li class="nav-item">
						<a class="nav-link" href="{% url 'lists:profile' %}"><img class="border border-2 rounded" src="https://bit.ly/3tvVkEo" style="height: 36px;"> <span class="ms-2">Профиль</span></a>
						</li>
					</ul>
					<!-- right navbar menu ends -->
				</div>
				<!-- navbar menu ends -->
			</div>
			</nav>
		</header>
		<!-- navigation bar ends -->

		{% block content %}
		{% endblock %}
	</body>
</html>

lists/templates/lists/base.html
<!doctype html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- Bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

		{% block title %}
		<title> title </title> 
		{% endblock %}

		<style>
			@import url('https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;400&display=swap');
			body {
				font-family: 'Roboto Slab';
                -webkit-background-size: cover;
                -moz-background-size: cover;
                -o-background-size: cover;
                 background-size: cover;
			}
			.content {
				position: absolute;
				top: 0px;
				bottom: 0;
				left: 0;
				right: 0;
				align: center;
				overflow-y: scroll;
			}
			.parallax {
				top: 56px;
				bottom: 0;
				left: 0;
				right: 0;
				position: fixed;
			}
			.mouse-parallax {
				height: 885px;
				position: relative;
				overflow: hidden;
			}
			.mouse-parallax-bg {
				position: absolute;
				background-image: url(https://mengembangkandiri.com/wp-content/uploads/2019/12/susan-yin-2JIvboGLeho-unsplash-768x513.jpg);
				background-position: center center;
				background-repeat: no-repeat;
				background-size: cover;
				width: 110%;
				height: 110%;
				transition: all 0.1s ease;
			}
		</style>

		{% block style %}
		{% endblock %}

	</head>
	<body>

		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

		{% block precontent %}
		{% endblock %}

		<!-- navigation bar starts -->
		<header>
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
			<div class="container-fluid">
				<!-- navbar brand starts -->
				<a class="navbar-brand" href="{% url 'home' %}">KNИGИ</a>
				<!-- navbar brand ends -->
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
				</button>
				<!-- navbar menu starts -->
				<div class="collapse navbar-collapse justify-content-between" id="navbarNav">
					<!-- left navbar menu starts -->
					<ul class="navbar-nav">
						<li class="nav-item">
							{% if user.is_authenticated %}
								<form method="post" action="{% url 'lists:library' %}">
									{% csrf_token %}
									<button style=" outline: none; border: 0; background: transparent;" onclick="location.href='{% url 'lists:library' %}'" class="nav-link">Библиотека</button>
									<input class="visually-hidden" name="username" type="search" value="{{ user.username }}">
								</form>
            				{% else %}
								<a class="nav-link" href="{% url 'login' %}">Библиотека</a>
            				{% endif %}
						</li>
						<li class="nav-item">
							{% if user.is_authenticated %}
								<a class="nav-link" href="{% url 'lists:profile' %}">Настройки</a>
            				{% else %}
								<a class="nav-link" href="{% url 'login' %}">Настройки</a>
            				{% endif %}
						</li>
					</ul>
					<!-- left navbar menu ends -->

					<!-- right navbar menu starts -->
					<ul class="navbar-nav ml-auto">
						{% if user.is_authenticated %}
						<li class="nav-item" style="padding-right: 40px;">
							<a class="btn btn-success ml-auto" href="{% url 'lists:profile' %}" role="button"> {{ user.username }} <img class="border border-2 rounded w-100" src="{{ avatar_url }}}" style="max-width: 40px; position: absolute; right: 100px; top: 8px;"></a>
						</li>
						{% endif %}
          				<li class="nav-item">
            				{% if user.is_authenticated %}
              					<a class="btn btn-outline-success ml-auto" href="{% url 'logout' %}" role="button">Выйти</a>
            				{% else %}
              					<a class="btn btn-outline-success ml-auto" href="{% url 'login' %}" role="button">Войти</a>
            				{% endif %}
          				</li>
        			</ul>
					<!-- right navbar menu ends -->
				</div>
				<!-- navbar menu ends -->
			</div>
			</nav>
		</header>
		<!-- navigation bar ends -->

		<div class="parallax">
			<div class="mouse-parallax">
				<div class="mouse-parallax-bg">
				</div>
			</div>
			<div class="content">
					{% block content %}
					{% endblock %}
					</div>
		</div>
		<script>
			let bg = document.querySelector('.mouse-parallax-bg');
			window.addEventListener('mousemove', function(e) {
				let x = e.clientX / window.innerWidth;
				let y = e.clientY / window.innerHeight;
				bg.style.transform = 'translate(-' + x * 50 + 'px, -' + y * 50 + 'px)';
			});
	    </script>
	</body>

</html>

lists/templates/lists/change_password.html
{% extends 'lists/base.html' %}
{% load crispy_forms_tags %}

{% block title%}
<title>Смена пароля</title>
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="container border border-1 rounded m-5" style="background-color: white;">
        <span class="row m-3 justify-content-start">
            Смена пароля
        </span>
        <div class="row border"></div>
        <div class="d-flex p-4">
            <div class="flex-fill d-flex flex-column" style="width: 30%;">
                <img class="border border-2 rounded w-100" src="{{ avatar_url }}}" style="max-width: 400px;">
            </div>
            <form method="POST" class="flex-fill d-flex flex-column ps-2 pe-2" style="width: 70%;">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn border border-2 w-100" style="margin-top: 20px" type="submit">Сохранить</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

lists/templates/lists/list.html
{% extends 'lists/base.html' %}

{% block title %}
<title> {{ list.name }} </title>
{% endblock %}

{% block style %}
<style>
    filter_icon {
        height: 38px; 
        width: 38px; 
        background-image: url(https://www.flaticon.com/svg/static/icons/svg/57/57164.svg); 
        background-size: 100%; 
        border: none;
    }
</style>
{% endblock %}

{% block content %}
<div class="row m-5 g-0">
    <form class="col-md row g-0 justify-content-center" method="get">
        <div class="col-6">
            <label for="inputSearch" class="visually-hidden">Search</label>
            <input class="form-control" name="book_search" type="search" id="inputSearch" placeholder="Введите название искомой книги">
        </div>
        <div class="col-auto">
            <button class="btn btn-light" type="submit">Поиск</button>
        </div>
        <div class="col-auto ms-2">
            <button class="btn" type="button" style="height: 38px; width: 38px; background-image: url(https://bit.ly/30Rw8f5); background-size: 100%; border: none;"></button>
        </div>
    </form>
</div>
<div class="container border border-1 rounded" style="background-color: white;">
    <span class="row m-3 justify-content-between">
        <span class="col-auto"> {{ list.name }} </span>
        <span class="col-auto text-secondary"> {{ list.size }} шт. </span>
    </span>
    <div class="row border"></div>
    <div class="row m-3">
        <table class="table table-borderless">
            <tbody>
                {% for book in list.books %}
                <tr class="m-2">
                    <td class="m-2">
                        <div class="d-flex border border-1 rounded justify-content-between">
                            <div class="m-2">
                                <img class="rounded thumb" src="{{ book.image_link }}">
                            </div>
                            <span class="flex-fill m-2">
                                    <p class="text-start"> {{ book.title }} ({{ book.pub_date.year }}) </p>
                                    <p class="text-start"> {{ book.authors }} </p>
                                    <p class="text-start"> {{ book.description }} </p>
                            </span>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

lists/templates/lists/lists.html
{% extends 'lists/base.html' %}

{% block title %}
<title> Списки </title>
{% endblock %}

{% block style %}
<style>
    a {
        text-decoration: none;
    }
    #overlay {
        position: fixed; 
        display: none;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
        width: 100%; 
        height: 100%; 
        background-color: rgba(0, 0, 0, .5); 
        z-index: 1;
    }
    #new-list {
        position: fixed;
        display: none;
        width: 30%;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        background-color: white;
        z-index: 2;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <form class="row g-0 m-5 justify-content-center" method="get">
        <div class="col-6">
            <label class="visually-hidden" for="inputSearch">Search</label>
            <input class="form-control" name="list_search" type="search" id="inputSearch" placeholder="Введите название искомого списка">
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-light">Поиск</button>
        </div>
    </form>
    <div class="row justify-content-center m-5">
        <ul class="list-group">
            {% for list in lists %}
            <li class="list-group-item">
                <a class="nav-link" href="{% url 'lists:list' %}" >
                    <div class="row justify-content-between">
                        <span class="col-auto text-body"> {{ list.name }} </span>
                        <span class="col-auto text-secondary"> {{ list.size }} шт. </span>
                    </div>
                </a>
            </li>
            {% endfor %}
            <li class="list-group-item">
                <button class="btn border border-2 w-100" type="button" onclick="on()">Создать список</button>
            </li>
        </ul>
    </div>
</div>
<div id="overlay" onclick="off()"></div>
<div class="container border border-2 rounded" id="new-list">
    <form class="col-auto p-2" action="{% url 'lists:listing' %}" method="POST">
        {% csrf_token %}
        <p class="row m-2">Новый список</p>
        <input class="row m-1 form-control" type="text" name="list_name" placeholder="Введите название" style="width: 97%" required>
        <button class="row m-1 btn btn-dark" type="submit" style="width: 97%;">Создать список</button>
    </form>
</div>
<script>
    function on() {
        document.getElementById('overlay').style.display = 'block';
        document.getElementById('new-list').style.display = 'block';
    }
    function off() {
        document.getElementById('overlay').style.display = 'none';
        document.getElementById('new-list').style.display = 'none';
    }
</script>
</a>
{% endblock %}

lists/templates/lists/profile.html
{% extends 'lists/base.html' %}
{% load crispy_forms_tags %}

{% block title%}
<title>Настройки</title>
{% endblock %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="container border border-1 rounded m-5" style="background-color: white;">
        <span class="row m-3 justify-content-start">
            Основная информация
        </span>
        <div class="row border"></div>
        <div class="d-flex p-4">
            <div class="flex-fill d-flex flex-column" style="width: 30%;">
                <img class="border border-2 rounded w-100" src="{{ avatar_url }}}" style="max-width: 400px;">
                <a href="https://gravatar.com/"><button class="btn border border-2 w-100">Сменить аватар</button></a>
            </div>
            <form method="POST" class="flex-fill d-flex flex-column ps-2 pe-2" style="width: 70%;">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn border border-2 w-100" style="margin-top: 20px" type="submit">Сохранить</button>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Необходимо сменить пароль? <a class="ml-2" href="{% url 'password' %}">Вам сюда</a>
                    </small>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}